import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Main from '../components/Main'

export default function Home() {
  return (
    <div className="container-fluid mx-auto sm:px-5 lg:px-6 bg-gray-50">
      <Head>
        <title>TaskForce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
        <Header/>
      {/* Main */}
      <main className="flex justify-center mx-auto px-8 sm:px-16">
        <Main/>
      </main>
      {/* Footer */}
      <div className="flex justify-center">
        <Footer/>
      </div>
    </div>
  )
}
